import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { addEnvironment, addRepository, loadConfig, selectRepository } from '../src/config.js';
import { extractGitActivity } from '../src/git.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';

test('Git registration, bounded history, tracked working tree and MCP share semantics', async t => {
  const root = await mkdtemp(join(tmpdir(), 'trace-git-'));
  t.after(() => rm(root, { recursive: true, force: true }));
  const repo = join(root, 'repo'); await mkdir(repo);
  const config = join(root, 'config.json');
  const git = (...args: string[]) => execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8', env: { ...process.env, GIT_AUTHOR_DATE: '2026-09-28T01:00:00Z', GIT_COMMITTER_DATE: '2026-09-28T02:00:00Z' } });
  git('init', '-q'); git('config', 'user.name', 'Fixture'); git('config', 'user.email', 'fixture@example.invalid');
  await addEnvironment({ name: 'codex', agent: 'codex', root }, config);
  await addRepository({ name: 'project', root: repo }, config);
  const selected = selectRepository(await loadConfig(config), 'project');
  assert.equal((await loadConfig(config)).environments.length, 1);
  await assert.rejects(addRepository({ name: 'project', root: repo }, config), /already exists/);
  await assert.rejects(addRepository({ name: 'invalid', root }, config), /working-tree root/);
  assert.throws(() => selectRepository({ version: 1, environments: [] }), /explicitly/);
  let result = await extractGitActivity(selected, { includeWorkingTree: true });
  assert.equal(result.incomplete, false); assert.equal(result.head, null);
  const strange = 'hello\nworld.txt';
  await writeFile(join(repo, strange), 'before\n'); git('add', '--', strange); git('commit', '-qm', 'first');
  git('mv', '--', strange, 'renamed.txt'); git('commit', '-qm', 'rename');
  await writeFile(join(repo, 'renamed.txt'), 'staged\n'); git('add', 'renamed.txt');
  await writeFile(join(repo, 'renamed.txt'), 'unstaged\n');
  await writeFile(join(repo, 'private.txt'), 'untracked secret');
  result = await extractGitActivity(selected, { from: '2026-09-28T00:00:00Z', to: '2026-09-29T00:00:00Z', includeWorkingTree: true, includePatch: true });
  assert.equal(result.incomplete, false, JSON.stringify(result.diagnostics));
  assert.equal(result.commits.length, 2);
  assert.equal(result.commits[0]?.timestamp, '2026-09-28T02:00:00.000Z');
  assert.ok(result.commits[1]?.changes?.some(c => c.path === strange && c.status === 'A'));
  assert.ok(result.commits[1]?.patch?.includes('+before'));
  assert.equal(result.workingTree?.changedAt, null);
  assert.deepEqual(result.workingTree?.changes, [{ status: 'MM', path: 'renamed.txt' }]);
  assert.ok(result.workingTree?.stagedPatch?.includes('+staged'));
  assert.ok(result.workingTree?.unstagedPatch?.includes('+unstaged'));
  assert.ok(!JSON.stringify(result).includes('untracked secret'));
  assert.equal((await extractGitActivity(selected, { to: '2026-09-28T02:00:00Z' })).commits.length, 0);
  assert.equal((await extractGitActivity(selected, { from: '2026-09-28T02:00:00.001Z' })).commits.length, 0);
  const limited = await extractGitActivity(selected, { limit: 1 });
  assert.equal(limited.hasMore, true); assert.ok(limited.diagnostics.includes('commit_limit'));
  assert.equal((await extractGitActivity(selected)).workingTree, null);
  assert.equal((await extractGitActivity(selected)).commits[0]?.patch, undefined);
  await assert.rejects(extractGitActivity(selected, { from: 'yesterday' }));
  await assert.rejects(extractGitActivity(selected, { from: '2026-09-29T00:00:00Z', to: '2026-09-28T00:00:00Z' }));
  const sub = join(repo, 'sub'); await mkdir(sub);
  await assert.rejects(addRepository({ name: 'sub', root: sub }, config), /working-tree root/);
  const cli = spawnSync(process.execPath, [resolve('dist/src/cli.js'), 'git-activity', '--repository', 'project', '--config', config], { encoding: 'utf8' });
  assert.equal(cli.status, 0, cli.stderr); assert.equal(JSON.parse(cli.stdout).commits.length, 2);
  const client = new Client({ name: 'git-test', version: '1' });
  try {
    await client.connect(new StdioClientTransport({ command: process.execPath, args: [resolve('dist/src/server.js')], env: { TRACE_CONFIG: config }, stderr: 'pipe' }));
    assert.ok((await client.listTools()).tools.some(tool => tool.name === 'extract_git_activity'));
    const response = await client.callTool({ name: 'extract_git_activity', arguments: { repository: 'project' } });
    assert.notEqual(response.isError, true);
    assert.equal(JSON.parse((response.content as { text: string }[])[0]!.text).commits.length, 2);
    assert.equal((await client.callTool({ name: 'extract_git_activity', arguments: { repository: 'missing' } })).isError, true);
  } finally { await client.close(); }
  // Large patches fail explicitly, keeping already available metadata.
  await writeFile(join(repo, 'large.txt'), 'x'.repeat(1100000)); git('add', 'large.txt'); git('commit', '-qm', 'large');
  const oversized = await extractGitActivity(selected, { includePatch: true });
  assert.equal(oversized.incomplete, true); assert.ok(oversized.diagnostics.includes('git_output_limit'));
});
